name: llm_playground
channels:
- conda-forge
dependencies:
- python=3.11
- ipykernel
- jupyterlab
- ipywidgets
- pip
- pip:
  - torch==2.7.0
  - transformers==4.52.0
  - datasets==3.6.0
  - evaluate==0.4.3
  - tiktoken==0.9.0
  - accelerate==1.7.0
  - sentencepiece==0.2.0
  - ipython==9.2.0
  - huggingface_hub==0.31.4

